### ISSUE TITLE
TypeError: Cannot read property 'm.room.message' of undefined

### ISSUE THREAD

**Issue by martindale** [matrix-org/matrix-appservice-bridge#154]
```
TypeError: Cannot read property 'm.room.message' of undefined
    at /opt/matrix-bridge/node_modules/matrix-appservice-bridge/lib/components/intent.js:764:49
    at tryCatcher (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:700:18)
    at _drainQueueStep (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/matrix-bridge/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at Console.console.(anonymous function) [as trace] (/opt/matrix-bridge/node_modules/debug-trace/debug-trace.js:97:15)
    at errorHandler (/opt/matrix-bridge/service.js:397:13)
    at tryCatcher (/opt/matrix-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/matrix-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/matrix-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/matrix-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/matrix-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/matrix-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/matrix-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by Half-Shot** [comment]
I think this got fixed a while ago during the TS port.
