### ISSUE TITLE
Cannot receive events / join private message room

### ISSUE THREAD

**Issue by qwetboy10** [matrix-org/matrix-appservice-bridge#173]
I'm using this simple code to try to test an appservice.
```js
//imports for appservice
const Cli = require("matrix-appservice-bridge").Cli;
const Bridge = require("matrix-appservice-bridge").Bridge;
const AppServiceRegistration = require("matrix-appservice-bridge").AppServiceRegistration;


const botName = "sms-bot";
const smsUserRegex = "@sms_.*";
const homeserverUrl = "https://trent.cf:8448";
const domain = "trent.cf";
const registrationFile = "registration.yaml";

new Cli({
    registrationPath: "registration.yaml",
    generateRegistration: function (reg, callback) {
        reg.setId(AppServiceRegistration.generateToken());
        reg.setHomeserverToken(AppServiceRegistration.generateToken());
        reg.setAppServiceToken(AppServiceRegistration.generateToken());
        reg.setSenderLocalpart(botName);
        reg.addRegexPattern("users", smsUserRegex, true);
        callback(reg);
    },
    run: function (port, config) {
        bridge = new Bridge({
            homeserverUrl: homeserverUrl,
            domain: domain,
            registration: registrationFile,

            controller: {
                onUserQuery: function (queriedUser) {
                    console.log('query: ' + JSON.stringify(queriedUser));
                    return {
                        name: queriedUser.localpart
                    };
                },

                onEvent: function (request, context) {
                    console.log('recv data ' + JSON.stringify(request.getData()));
                },
                onLog: function (line, isError) {
                    console.log(line + (isError ? " error" : ""));
                }
            }
        });
        console.log("Matrix-side listening on port %s", port);
        bridge.run(port, config);
    }
}).run();
```
Here is my registration.yaml
```yaml
namespaces:
  users:
    - exclusive: true
      regex: '@sms_.*'
  aliases: []
  rooms: []
url: 'http://flowroute:5000'
sender_localpart: sms-bot
rate_limited: true
protocols: null
```
This is running in a docker container (the flowroute url goes to the container). When I run the appservice I get the below output
```
flowroute_1  | Matrix-side listening on port 5000
flowroute_1  | query: {"userId":"@sms_3:trent.cf","localpart":"sms_3","host":"trent.cf","_data":{}}
flowroute_1  | [-] POST https://trent.cf:8448/_matrix/client/r0/register (AS) Body: "{\"username\":\"sms_3\"}"
flowroute_1  | [-] POST https://trent.cf:8448/_matrix/client/r0/register (AS) HTTP 200 "{\"user_id\": \"@sms_3:trent.cf\", \"home_server\": \"trent.cf\", \"access_toke
flowroute_1  | [-] PUT https://trent.cf:8448/_matrix/client/r0/profile/%40sms_3%3Atrent.cf/displayname (@sms_3:trent.cf) Body: "{\"displayname\":\"sms_3\"}"
flowroute_1  | [-] PUT https://trent.cf:8448/_matrix/client/r0/profile/%40sms_3%3Atrent.cf/displayname (@sms_3:trent.cf) HTTP 200 "{}"
flowroute_1  | ::ffff:172.23.0.4 - - [20/Jul/2020:20:53:33 +0000] "GET /users/%40sms_3%3Atrent.cf?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.16.0"
flowroute_1  | 
flowroute_1  | ::ffff:172.23.0.4 - - [20/Jul/2020:20:53:33 +0000] "PUT /transactions/3?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.16.0"
flowroute_1  | 
flowroute_1  | recv data {"age":570,"content":{"is_direct":true,"membership":"invite"},"event_id":"$zEepqVLGbAzGE6Bx4xzo9y_q_khbxBm5XAPJGOsJAA0","origin_server_ts":1595278413325,"room_id":"!oxPHbsNrbKCAMHHYzo:trent.cf","sender":"@tristan:trent.cf","state_key":"@sms_3:trent.cf","type":"m.room.member","unsigned":{"age":570},"user_id":"@tristan:trent.cf"}
```
The problem is that after that there are no more events. I try to send messages but nothing happens in the logs. Also, the user is still marked as invited in the room.

**Comment by Half-Shot** [comment]
The bridge will not automatically join the room for you, you will need to join it using the Intent class. https://matrix-org.github.io/matrix-appservice-bridge/1.13.1/Bridge.html#getIntent and then calling https://matrix-org.github.io/matrix-appservice-bridge/1.13.1/Intent.html#join

**Comment by qwetboy10** [comment]
I tried to do that but I started getting the below error:
```Unhandled rejection TypeError: entry.dataReady.finally is not a function
    at EventQueueSingle._takeNext (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/components/event-queue.js:88:32)
    at Object.keys.forEach (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/components/event-queue.js:76:22)
    at Array.forEach (<anonymous>)
    at EventQueueSingle.consume (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/components/event-queue.js:73:35)
    at Bridge.__onEvent (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/bridge.js:729:17)
    at Bridge._onEvent (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/bridge.js:694:30)
    at emitOne (events.js:116:13)
    at AppService.emit (events.js:211:7)
    at AppService.onTransaction (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice/lib/app-service.js:203:18)
    at Layer.handle [as handle_request] (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/layer.js:95:5)
    at /home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/index.js:281:22
    at param (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/index.js:354:14)
    at param (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/index.js:365:14)
```
I'm not sure what I did to cause this and I can't get it to go away. (I might be that I updated my dependencies )

**Comment by qwetboy10** [comment]
Once I fixed the second issue I could receive events. I decided to move the second error to its own issue because it seemed like a seperate thing. Thanks for the help
