### ISSUE TITLE
Problem with promises in event-queue.js

### ISSUE THREAD

**Issue by qwetboy10** [matrix-org/matrix-appservice-bridge#174]
When I tried to use this library I started getting the below error
```
Unhandled rejection TypeError: entry.dataReady.finally is not a function
    at EventQueueSingle._takeNext (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/components/event-queue.js:88:32)
    at Object.keys.forEach (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/components/event-queue.js:76:22)
    at Array.forEach (<anonymous>)
    at EventQueueSingle.consume (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/components/event-queue.js:73:35)
    at Bridge.__onEvent (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/bridge.js:729:17)
    at Bridge._onEvent (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice-bridge/lib/bridge.js:694:30)
    at emitOne (events.js:116:13)
    at AppService.emit (events.js:211:7)
    at AppService.onTransaction (/home/tristan/momentum-connect/flowroute-appservice/node_modules/matrix-appservice/lib/app-service.js:203:18)
    at Layer.handle [as handle_request] (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/layer.js:95:5)
    at /home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/index.js:281:22
    at param (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/index.js:354:14)
    at param (/home/tristan/momentum-connect/flowroute-appservice/node_modules/express/lib/router/index.js:365:14)
```
I managed to fix this by changing line 88 in matrix-appservice-bridge/lib/components/event-queue.js. I changed `entry.dataReady.finally(() => this._takeNext(identifier));` to `entry.dataReady.then(() => this._takeNext(identifier));`. This appears to have fixed the problem for me. However, I didn't submit a pull request because I don't really know what I'm doing in js and I'm worried I fixed this bug by causing a different one. For now though everything seems to be working fine.

**Comment by Half-Shot** [comment]
I'm hesitant to say that should fix it, .then and .finally should both be accessible on a promise. Though that being said I am not sure how you ended up with a non-promise value in the queue :thinking:

**Comment by Half-Shot** [comment]
@qwetboy10 is this still a problem on the latest version of the bridge?

**Comment by qwetboy10** [comment]
Sorry, I no longer have access to the code that pertains to the issue (it's from an old internship.)
