### ISSUE TITLE
Unable to fetch parent event Error: No member in room, cannot handle edit

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-bridge#379]
Obviously this cannot be true, or we wouldn't be able to see the child event. There must be a bug in our system somewhere.

```
Dec  6 11:50:34 lethe docker-slack-bridge[912]: Dec-6 11:50:34.280 WARN bridge Rejecting $PQmS_CE6KHntik3o7YEuv2jhc89mF-9QltsITCMaYhQ: Unable to fetch parent event $rmPzmoqCi1SyL2yu7zVuJieZoBmLfIqZUFsEHd_3Su8 Error: No member in room, cannot handle edit
Dec  6 11:50:34 lethe docker-slack-bridge[912]:     at Bridge.validateEditEvent (/usr/src/app/node_modules/matrix-appservice-bridge/lib/bridge.js:830:23)
Dec  6 11:50:34 lethe docker-slack-bridge[912]:     at runMicrotasks (<anonymous>)
Dec  6 11:50:34 lethe docker-slack-bridge[912]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Dec  6 11:50:34 lethe docker-slack-bridge[912]:     at async Bridge.onEvent (/usr/src/app/node_modules/matrix-appservice-bridge/lib/bridge.js:878:18)
```

**Comment by Half-Shot** [comment]
May be solved by https://github.com/matrix-org/matrix-doc/issues/3547
